### ISSUE TITLE
exynos7870: add support for a3y17lte

### ISSUE THREAD

**Issue by dkey5** [TALUAtGitHub/android_kernel_samsung_exynos7870#3]
https://github.com/exynos7870-dev/android_kernel_samsung_universal7870/tree/samsung-osrc

dts are already attached in arch/arm64/boot/dts. Will it work if we add defconfig?

**Comment by TALUAtGitHub** [comment]
> dts are already attached in arch/arm64/boot/dts. Will it work if we add defconfig?
Well, I guess it should, although there might be something that's broken since there's no testing on any device other than the gtaxl devices with the huge changes I've applied.
It's entirely up to you to test.
